import React from 'react';

import type { Metadata } from 'next';

import { CssBaseline } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

import Navigation from '@/components/navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh">
      <CssBaseline />
      <body>
        <AppRouterCacheProvider>
          <Navigation>{children}</Navigation>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
